const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS = "BEST POPULAR MOVIES AND SERIALS";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIME = "CHECK MOVIE\nSHOWTIMES";
const SHOW_CASES_TITLE = "SHOWCASES";
const SHOW_CASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTOR_TITLE = "BEST ACTORS";
const BEST_ACTOR_SEE_MORE = "MORE ACTORES";
const BEST_POPULAR_MOVIES = "BEST POPULAR MOVIES AND SERIALS";

const MOVIE_DETAILS_SCREEN_ACTOR_TITLE = "ACTORS";
const MOVIE_DETAILS_SCREEN_CREATOR_TITLE = "CREATORS";
const MOVIE_DETAILS_SCREEN_CREATORS_SEE_MORE = "MORE CREATORS";
const MOVIE_DETAILS_STORYLINE_TITLE = "STORY LINE";
const RELATED_MOVIES = "RELATED MOVIES";